// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"code.cloudfoundry.org/gorouter/handlers"
)

type FakeRouteServiceProxy struct {
	ServeHTTPStub        func(responseWriter http.ResponseWriter, request *http.Request)
	serveHTTPMutex       sync.RWMutex
	serveHTTPArgsForCall []struct {
		responseWriter http.ResponseWriter
		request        *http.Request
	}
}

func (fake *FakeRouteServiceProxy) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	fake.serveHTTPMutex.Lock()
	fake.serveHTTPArgsForCall = append(fake.serveHTTPArgsForCall, struct {
		responseWriter http.ResponseWriter
		request        *http.Request
	}{responseWriter, request})
	fake.serveHTTPMutex.Unlock()
	if fake.ServeHTTPStub != nil {
		fake.ServeHTTPStub(responseWriter, request)
	}
}

func (fake *FakeRouteServiceProxy) ServeHTTPCallCount() int {
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	return len(fake.serveHTTPArgsForCall)
}

func (fake *FakeRouteServiceProxy) ServeHTTPArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.serveHTTPMutex.RLock()
	defer fake.serveHTTPMutex.RUnlock()
	return fake.serveHTTPArgsForCall[i].responseWriter, fake.serveHTTPArgsForCall[i].request
}

var _ handlers.RouteServiceProxy = new(FakeRouteServiceProxy)
